version: "3.9"
services:
  cache:
    container_name: cache
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status/health"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      SENTRY_URI: ${SENTRY_URI}
    volumes:
      - charts:/app/charts
    ports:
      - "8000:8000"
volumes:
  charts: